#Change the server
server:
#  port: 3000
  port: 8820 #default

#Run application without web server
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: amigos
    password: password
  jpa:
    hibernate:
    #      ddl-auto: create-drop
          ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    #    web-application-type: none
    web-application-type: servlet #default

